import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, writeFile, readdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { promisify } from "node:util";
import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import sharp from "sharp";
import { inspectGpx } from "../scripts/content-gpx.mjs";
import { normalizeImpact, publicSession, validateReview } from "../scripts/target-records.mjs";
import { detectImpacts, detectionRequest } from "../scripts/target-vision.mjs";

const run=promisify(execFile);
const gpx=`<gpx xmlns="http://www.topografix.com/GPX/1/1" version="1.1"><trk><name>Morning &amp; evening</name><trkseg><trkpt lon="-73.97" lat="40.66"><time>2026-03-24T10:00:00Z</time><extensions><secret>device</secret></extensions></trkpt><trkpt lat="40.661" lon="-73.971"><time>2026-03-24T10:02:00Z</time></trkpt></trkseg></trk></gpx>`;
const calibration={center:[50,50],rings:[[.2,50,50,8,8],[1,50,50,40,40]]};
const mark={id:"impact-1",x:58,y:50,uncertain:true,note:"Possible merged tear"};
const record={id:"photo-"+"a".repeat(24),digest:"a".repeat(64),name:"Target",date:"2026-03-24",exifDate:"2026-03-24",capturedAt:null,width:100,height:100,mime:"image/jpeg",marks:[mark],excluded:[{id:"pin-1",x:10,y:5,uncertain:false,note:"Hanging pin"}],calibration};

test("GPX uses XML parsing, validates timing and strips private extensions",()=>{
  const parsed=inspectGpx(gpx,"cycling");
  assert.equal(parsed.name,"Morning & evening");assert.equal(parsed.points.length,2);assert.ok(parsed.hasTiming);
  assert.ok(!parsed.xml.includes("secret"));assert.match(parsed.xml,/Morning &amp; evening/);
  const untimed=gpx.replace(/<time>[^<]+<\/time>/g,"");
  assert.throws(()=>inspectGpx(untimed,"cycling"),/timestamps/);
  assert.equal(inspectGpx(untimed,"sailing").hasTiming,false);
  assert.throws(()=>inspectGpx(gpx.replace('lat="40.66"','lat="100"'),"cycling"),/coordinates/);
  assert.throws(()=>inspectGpx("<gpx><trk></gpx>","cycling"));
  assert.throws(()=>inspectGpx("<gpx/>","sailing"),/two track/);
});

test("photo normalization preserves axes, misses, uncertainty, and exclusions",()=>{
  assert.deepEqual(normalizeImpact({x:50,y:50},calibration),{x:0,y:0});
  assert.deepEqual(normalizeImpact({x:50,y:10},calibration),{x:0,y:1});
  assert.equal(normalizeImpact({x:94,y:50},calibration).x,1.1);
  const session=publicSession(record);
  assert.equal(session.ends[0].endNumber,null);assert.equal(session.shotOrder,"unknown");
  assert.equal(session.ends[0].shots.length,1);assert.equal(session.ends[0].shots[0].uncertain,true);
  assert.ok(!("startedAt" in session));assert.equal(session.equipment.arrowId,null);
  assert.ok(!JSON.stringify(session).includes("Hanging pin"));
  const feedbackRecord = {...record, reviewFeedback:"Private request for revision", reviewState:"ready", marks:[{...mark,feedback:"Two arrows here",observedCount:2}]};
  const feedbackSession=publicSession(feedbackRecord);
  assert.equal(feedbackSession.ends[0].shots[0].observedCount,2);
  assert.ok(!JSON.stringify(feedbackSession).includes("Private request"));
  assert.ok(!JSON.stringify(feedbackSession).includes("Two arrows"));
  assert.throws(()=>validateReview({...record,reviewState:"invalid"}),/review state/);
  assert.throws(()=>publicSession({...record,date:"2026-02-30"}),/date/);
  assert.throws(()=>validateReview({...record,marks:[{...mark,x:NaN}]}),/position/);
});

test("vision request preserves image frame and pin rule; failures don't masquerade as results",async()=>{
  const request=detectionRequest(record,Buffer.from("image"));
  assert.equal(request.store,false);assert.equal(request.text.format.strict,true);
  assert.equal(request.input[0].content[1].detail,"original");
  assert.match(request.input[0].content[0].text,/hanging-pin/);
  const result={isSupportedTarget:true,note:"",center:{x:50,y:50},rings:[],impacts:[],hangingHoles:[]};
  const decoded=await detectImpacts(record,Buffer.from("image"),{apiKey:"test-only",fetchImpl:async()=>({ok:true,json:async()=>({status:"completed",output:[{content:[{type:"output_text",text:JSON.stringify(result)}]}]})})});
  assert.deepEqual(decoded,result);
  await assert.rejects(detectImpacts(record,Buffer.from("image"),{}),/API key/);
  await assert.rejects(detectImpacts(record,Buffer.from("image"),{apiKey:"test",fetchImpl:async()=>({ok:false,status:401})}),/rejected/);
  await assert.rejects(detectImpacts(record,Buffer.from("image"),{apiKey:"test",fetchImpl:async()=>({ok:true,json:async()=>({status:"incomplete"})})}),/did not finish/);
});

test("content command imports, caches, applies corrections, preserves history, and is idempotent",async()=>{
  const temporary=await mkdtemp(join(tmpdir(),"site-content-test-"));
  const inbox=join(temporary,"inbox"),output=join(temporary,"content"),cache=join(temporary,"cache");
  for(const folder of ["targets","cycling","sailing"])await mkdir(join(inbox,folder),{recursive:true});
  await mkdir(join(output,"archery"),{recursive:true});await mkdir(cache,{recursive:true});
  await writeFile(join(output,"archery/session-index.json"),JSON.stringify([{id:"sample-old",file:"unused.json"}]));
  await writeFile(join(inbox,"cycling/ride.gpx"),gpx);
  await writeFile(join(inbox,"sailing/sail.gpx"),gpx.replace(/<time>[^<]+<\/time>/g,""));
  const image=await sharp({create:{width:100,height:100,channels:3,background:"white"}}).jpeg().toBuffer();
  const digest=createHash("sha256").update(image).digest("hex"),id=`photo-${digest.slice(0,24)}`;
  await writeFile(join(inbox,"targets/target.jpeg"),image);
  const cached={...record,id,digest,status:"review",revision:1};
  await writeFile(join(cache,`${id}.json`),JSON.stringify(cached));await writeFile(join(cache,`${id}.image`),image);
  const env={...process.env,TARGET_STORE:cache,CONTENT_OUTPUT_DIR:output,OPENAI_API_KEY:"",CONTENT_WEATHER_OFFLINE:"1"};
  const command=resolve("scripts/update-content.mjs");
  const result=await run(process.execPath,[command,"--folder",inbox],{env});
  assert.match(result.stdout,/4 added\/updated/);
  assert.deepEqual(JSON.parse(await readFile(join(output,"pages/labs.json"),"utf8")),[]);
  const indexPath=join(output,"archery/session-index.json");
  const index=JSON.parse(await readFile(indexPath,"utf8"));assert.equal(index.length,1);assert.equal(index[0].id,id);
  assert.equal((await readdir(join(inbox,"review"))).length,2);
  const before=await readFile(indexPath,"utf8");
  await writeFile(join(inbox,"cycling/renamed.gpx"),gpx);
  const again=await run(process.execPath,[command,"--folder",inbox],{env});assert.match(again.stdout,/0 added\/updated/);
  assert.equal(await readFile(indexPath,"utf8"),before);
  assert.equal(JSON.parse(await readFile(join(output,"rides/ride-index.json"),"utf8")).length,1);
  await writeFile(join(inbox,"sailing/sail.gpx.json"),JSON.stringify({name:"Club evening",boat:{class:"J/80"},sailType:"club",notes:"Owner note"}));
  await run(process.execPath,[command,"--folder",inbox,"--only","sailing"],{env});
  let sails=JSON.parse(await readFile(join(output,"sails/sail-index.json"),"utf8"));
  assert.equal(sails.length,1);assert.equal(sails[0].label,"Club evening");
  assert.equal(sails[0].eventDetails.boat.class,"J/80");assert.equal(sails[0].eventDetails.sailType,"club");
  assert.equal(sails[0].eventDetails.durationSeconds,null);
  await writeFile(join(inbox,"sailing/sail.gpx.json"),JSON.stringify({boat:{class:"J/24"},sailType:"race"}));
  await run(process.execPath,[command,"--folder",inbox,"--only","sailing"],{env});
  sails=JSON.parse(await readFile(join(output,"sails/sail-index.json"),"utf8"));
  assert.equal(sails.length,1);assert.equal(sails[0].eventDetails.boat.class,"J/24");
  assert.equal(sails[0].eventDetails.notes,null);
  await writeFile(join(inbox,"targets/target.jpeg.json"),JSON.stringify({name:"Corrected target",date:"2026-03-25"}));
  await run(process.execPath,[command,"--folder",inbox],{env});
  const session=JSON.parse(await readFile(join(output,"archery/sessions",`${id}.json`),"utf8"));
  assert.equal(session.name,"Corrected target");assert.equal(session.recordedDate,"2026-03-25");assert.equal(session.source.dateSource,"manual");
  await writeFile(join(inbox,"cycling/invalid.gpx"),"<gpx/>");
  await assert.rejects(run(process.execPath,[command,"--folder",inbox],{env}),error=>error.code===1 && error.stderr.includes("two track"));
  assert.equal(JSON.parse(await readFile(join(output,"rides/ride-index.json"),"utf8")).length,1);
  const dryFolder=join(temporary,"empty");
  await run(process.execPath,[command,"--dry-run","--folder",dryFolder],{env});
  await assert.rejects(readFile(join(dryFolder,"targets")),{code:"ENOENT"});
});
